int rled=13;
int gled=12;
int bled=11;
int slowb=500;
int fastb=100;
     
void setup()
{
  pinMode(rled, OUTPUT);
  pinMode(gled, OUTPUT);
  pinMode(bled, OUTPUT);
}

void loop()
{
  digitalWrite(rled, HIGH);
  delay(fastb);
  digitalWrite(rled, LOW);
  delay(fastb);
  digitalWrite(rled, HIGH);
  delay(fastb);
  digitalWrite(rled, LOW);
  delay(fastb);
  digitalWrite(rled, HIGH);
  delay(fastb);
  digitalWrite(rled, LOW);
  delay(fastb);
  digitalWrite(rled, HIGH);
  delay(fastb);
  digitalWrite(rled, LOW);
  delay(fastb);
  digitalWrite(rled, HIGH);
  delay(fastb);
  digitalWrite(rled, LOW);
  delay(fastb);
  
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  digitalWrite(gled, HIGH);
  delay(slowb);
  digitalWrite(gled, LOW);
  delay(slowb);
  
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
  digitalWrite(bled, HIGH);
  delay(fastb);
  digitalWrite(bled, LOW);
  delay(fastb);
    
  
}